Traceback (most recent call last):
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\Bugs\099\original_code_snippet.py", line 14, in <module>
    checkpoint_callback()
  File "C:\Users\Mehil Shah\Downloads\Research Projects\Bug Reproducibility\Bugs\099\original_code_snippet.py", line 5, in checkpoint_callback
    return ModelCheckpoint(
TypeError: ModelCheckpoint.__init__() got an unexpected keyword argument 'filepath'
